#!/bin/sh
browser="brave"

echo "what applicatin"
# read -r application

nc -z 8.8.8.8 53 >/dev/null 2>&1
online=$?
if [ $online -eq 0 ]; then
    "$browser" https://wiki.artixlinux.org/
else 
    echo "Go to hell"
fi
